---

- name: Install tar & gzip
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - tar
    - gzip

- name: Extract backend build (include copy)
  unarchive:
    src: artifact.tar.gz
    dest: ~/

- name: Start application
  shell: |
    npm install
    pm2 stop default
    pm2 start npm --start