---

- name: Install tar & gzip
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - tar
    - gzip
    - unzip

- name: Create app directory
  shell: |
    mkdir -p /home/ubuntu/app

- name: Copy app artifact
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/app.tar.gz

- name: Copy inventory
  copy:
    src: ~/project/.circleci/ansible/inventory.txt
    dest: /home/ubuntu/inventory.txt

- name: Extract backend build (include copy)
  become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/app
    
- name: Change owner to ubuntu
  become: true
  file:
    path: /home/ubuntu/app
    owner: ubuntu
    group: ubuntu
    recurse: yes

- name: Start application
  become: true
  become_user: ubuntu
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    cd /home/ubuntu/app
    npm install
    pm2 stop default
    npm run prestart:prod
    pm2 start npm -- start
