---

- name: Install tar & gzip
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - tar
    - gzip
    - unzip

- name: Create app directory
  shell: |
    mkdir -p /home/ubuntu/app

- name: Extract backend build (include copy)
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/app

- name: Check env
  shell: |
    echo $TYPEORM_PORT
    echo $TYPEORM_USERNAME
    
# - name: Start application
#   shell: |
#     cd /home/ubuntu/app
#     npm install
#     pm2 stop default
#     pm2 start npm -- start