---

- name: Install tar & gzip
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - tar
    - gzip
    - unzip

- name: Extract backend build (include copy)
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/app

- name: Start application
  shell: |
    cd /home/ubuntu/app
    npm install
    pm2 stop default
    pm2 start npm --start