---

- name: Install tar & gzip
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - tar
    - gzip
    - unzip

- name: Create app directory
  shell: |
    mkdir -p /home/ubuntu/app

- name: Copy app artifact
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/app.tar.gz

- name: Copy inventory
  copy:
    src: ~/project/.circleci/ansible/inventory.txt
    dest: /home/ubuntu/inventory.txt

- name: Extract backend build (include copy)
  become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/app
    
- name: Change owner to ubuntu
  become: true
  file:
    path: /home/ubuntu/app
    owner: ubuntu
    group: ubuntu
    recurse: yes
    
- name: Start application
  become: true
  become_user: ubuntu
  shell: |
    cd /home/ubuntu/app
    sudo npm install
    sudo pm2 stop default
    sudo npm run prestart:prod
    sudo pm2 start npm -- start

- name: Try ping
  shell: |
    export BACKEND_IP=$(tail -1 /home/ubuntu/inventory.txt)
    echo ${BACKEND_IP}
    export API_URL="http://${BACKEND_IP}:3030"
    echo "${API_URL}"
    if curl "${API_URL}/api/status" | grep "ok"
    then
        return 0
    else
        return 1
    fi